% save data (save command is taken)
%
ag1string=[];
for ag1=ag1s
 ag1string=[ag1string,'-',num2str(ag1)];
end
%
fname = [ 'a1', ag1string,...
          '|n=', num2str(nbcr),...
          '|mfr=', num2str(bcmemfr),...
          '|o=', num2str(occl),...
          '|k12=', num2str(bcr(1).k2),...
          '|k22=', num2str(bcr(2).k2),...
          '|dk1=', num2str(dkpenalty(1)),...
          '|qt=', num2str(qtcell) ] ;
%
save('-mat',[fname,'.mat'], 'mbcr', 'nrun', 'bcmemfr', 'occl', 'nbcrs', 'dkpenalty', 'mbcsave', 'affinity', 'mbcouttot', 'agsout' )
